### ISSUE TITLE
Memory reclaimation issues

### ISSUE THREAD

**Issue by ianamason** [revng/llvmcpy#26] opened 2018-06-18 14:27 UTC
Releasing memory buffers appears to cause problems.
Is this known or user error?
```
def fileToModule(path):
    buffer = create_memory_buffer_with_contents_of_file(path)
    context = get_global_context()
    module = context.parse_ir(buffer)
    buffer.dispose()
    return module

```
The call to `dispose` usually crashes my python process with a SIGSEGV.
Sometimes with a 
```
Python(20023,0x7fff95820380) malloc: *** error for object 0x7fe2da831000: pointer being freed was not allocated
```

I also think the translation of `LLVMContextDispose` into a getter seems dubious:

```
class Context(object):
...
    def get_dispose(self):
        """See LLVMContextDispose"""
        return libLLVM.LLVMContextDispose(self.in_ptr())
```

**Comment by aleclearmind** [comment] 2018-06-18 20:36
Uhm, I can reproduce that. Can you please verify that the equivalent calls to the LLVM-C API functions do not produce the same behavior? Just to ensure it's due to something we did and not an LLVM issue itself. Using a debug build might help, maybe we're triggering some assertion.

As per `get_dispose`, I see there are way too many methods starting with `get_`. There has to be a bug, can you please open a new issue for that?

Thanks for reporting this.

**Comment by ianamason** [comment] 2018-06-18 20:41
I  did a bit of investigating [here](https://github.com/ianamason/llvm_bc_parsing_example) and the code runs smoothly. I was gonna valgrind it too, but alas discovered that valgrind no longer runs on os x. So I will have to investigate inside a vagrant box.

Will open the other issue.

**Comment by ianamason** [comment] 2018-09-04 16:11
Thanks for the info @viktormalik!

**Comment by aleclearmind** [comment] 2018-09-07 18:28
@ianamason can you try to set up an equivalent example using `LLVMParseBitcode2`, for future reference.

Then I guess, we can consider this issue closed. We should probably open an issue in LLVM.

**Comment by ianamason** [comment] 2018-09-07 23:47
I will see if I can get to this next week @aleclearmind

**Comment by aleclearmind** [comment] 2019-05-20 10:34
Any updates on this side?

**Comment by ianamason** [comment] 2019-05-20 14:48
Nope never got to it. My in pile overfloweth.

**Comment by aleclearmind** [comment] 2019-05-23 22:21
OK, closing this. Feel free to reopen if needed.

**Closed by aleclearmind** 2019-05-23 22:21 UTC
